# Generated by Django 3.1.4 on 2020-12-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_temp', models.FloatField(default=0)),
                ('min_temp', models.FloatField(default=0)),
                ('average', models.FloatField(blank=True, default=0)),
                ('median', models.FloatField(blank=True, default=0)),
                ('city', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
