# Generated by Django 3.1.4 on 2020-12-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_min_degrees', models.FloatField(default=0)),
                ('_max_degrees', models.FloatField(default=0)),
                ('_city', models.CharField(max_length=255)),
                ('_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['_time'],
            },
        ),
    ]
