# Generated by Django 3.1.4 on 2020-12-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='_average',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='temperature',
            name='_median',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
