# Generated by Django 3.1.4 on 2020-12-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='description',
            field=models.CharField(default='sunny', max_length=255),
        ),
    ]
