# Generated by Django 3.1.4 on 2020-12-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0002_auto_20201215_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='_max_degrees',
            new_name='_max_temp',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='_min_degrees',
            new_name='_min_temp',
        ),
    ]
