# Generated by Django 3.1.4 on 2020-12-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0003_auto_20201215_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['time']},
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='_average',
            new_name='average',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='_max_temp',
            new_name='max_temp',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='_median',
            new_name='median',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='_min_temp',
            new_name='min_temp',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='_time',
            new_name='time',
        ),
    ]
